import type { PriceCatalog } from "./types";

export const samplePriceCatalog: PriceCatalog = {
  source: {
    id: "demo-2026-msk",
    name: "Демо-прайс Московская область",
    kind: "manual",
    supplierName: "Демо-поставщик",
    importedAt: "2026-06-05T00:00:00.000Z",
  },
  items: [
    {
      id: "price-wall-gasblock400",
      sourceId: "demo-2026-msk",
      code: "wall.gasblock400.m2",
      category: "Коробка",
      name: "Наружная стена из газоблока 400 мм",
      unit: "m2",
      materialUnitPrice: 3400,
      laborUnitPrice: 2100,
      requiresReview: false,
    },
    {
      id: "price-partition-gasblock100",
      sourceId: "demo-2026-msk",
      code: "partition.gasblock100.m2",
      category: "Коробка",
      name: "Перегородка из газоблока 100 мм",
      unit: "m2",
      materialUnitPrice: 1250,
      laborUnitPrice: 1300,
      requiresReview: false,
    },
    {
      id: "price-window-basic",
      sourceId: "demo-2026-msk",
      code: "window.basic.pcs",
      category: "Окна и двери",
      name: "Окно: поставка и монтаж",
      unit: "pcs",
      materialUnitPrice: 18000,
      laborUnitPrice: 4500,
      requiresReview: true,
    },
    {
      id: "price-door-basic",
      sourceId: "demo-2026-msk",
      code: "door.basic.pcs",
      category: "Окна и двери",
      name: "Дверь: поставка и монтаж",
      unit: "pcs",
      materialUnitPrice: 12000,
      laborUnitPrice: 3500,
      requiresReview: false,
    },
    {
      id: "price-floor-draft",
      sourceId: "demo-2026-msk",
      code: "floor.draft.m2",
      category: "Отделка",
      name: "Черновой пол по площади помещения",
      unit: "m2",
      materialUnitPrice: 850,
      laborUnitPrice: 700,
      requiresReview: false,
    },
    {
      id: "price-roof-metal",
      sourceId: "demo-2026-msk",
      code: "roof.metal.m2",
      category: "Кровля",
      name: "Металлочерепица: материал и монтаж",
      unit: "m2",
      materialUnitPrice: 2300,
      laborUnitPrice: 1700,
      requiresReview: false,
    },
    {
      id: "price-foundation-slab",
      sourceId: "demo-2026-msk",
      code: "foundation.slab.concrete.m3",
      category: "Фундамент",
      name: "Бетон для монолитной плиты",
      unit: "m3",
      materialUnitPrice: 7600,
      laborUnitPrice: 3800,
      requiresReview: false,
    },
  ],
};
