import type { Project } from "./types";

export const sampleHouseProject: Project = {
  id: "sample-house-142",
  name: "Sample house 142 m2",
  kind: "house",
  currency: "RUB",
  levels: [
    {
      id: "foundation",
      name: "Foundation",
      kind: "foundation",
      elements: [
        {
          id: "foundation-slab-1",
          kind: "foundation-segment",
          name: "Main slab",
          includeInEstimate: true,
          areaM2: 90,
          thicknessMeters: 0.3,
          perimeterMeters: 38,
          technologyPackageId: "foundation-slab",
        },
      ],
    },
    {
      id: "floor-1",
      name: "Floor 1",
      kind: "floor-1",
      heightMeters: 3,
      elements: [
        {
          id: "wall-north",
          kind: "wall",
          name: "North external wall",
          includeInEstimate: true,
          start: { x: 0, y: 0 },
          end: { x: 10, y: 0 },
          heightMeters: 3,
          thicknessMeters: 0.4,
          technologyPackageId: "wall-gasblock-400",
        },
        {
          id: "wall-east",
          kind: "wall",
          name: "East external wall",
          includeInEstimate: true,
          start: { x: 10, y: 0 },
          end: { x: 10, y: 8 },
          heightMeters: 3,
          thicknessMeters: 0.4,
          technologyPackageId: "wall-gasblock-400",
        },
        {
          id: "partition-1",
          kind: "partition",
          name: "Living room partition",
          includeInEstimate: true,
          start: { x: 2, y: 1 },
          end: { x: 2, y: 7 },
          heightMeters: 3,
          thicknessMeters: 0.1,
          technologyPackageId: "partition-gasblock-100",
        },
        {
          id: "window-1",
          kind: "window",
          name: "North window",
          includeInEstimate: true,
          wallId: "wall-north",
          widthMeters: 1.5,
          heightMeters: 1.4,
          count: 2,
          technologyPackageId: "window-basic",
        },
        {
          id: "door-1",
          kind: "door",
          name: "Entrance door",
          includeInEstimate: true,
          wallId: "wall-east",
          widthMeters: 0.9,
          heightMeters: 2.1,
          count: 1,
          technologyPackageId: "door-basic",
        },
        {
          id: "room-1",
          kind: "room",
          name: "Floor area",
          includeInEstimate: true,
          areaM2: 80,
          floorFinishPackageId: "floor-draft",
        },
      ],
    },
    {
      id: "roof",
      name: "Roof",
      kind: "roof",
      elements: [
        {
          id: "roof-main",
          kind: "roof-segment",
          name: "Main roof slopes",
          includeInEstimate: true,
          areaM2: 120,
          slopeCoefficient: 1.12,
          technologyPackageId: "roof-metal",
        },
      ],
    },
  ],
};
